apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daystrom-mini

resources:
  - namespace.yaml
  - configmaps.yaml
  - redis.yaml
  - postgres.yaml
  - otel-collector.yaml
  - llama-cpp.yaml
  - mock-safety.yaml
  - request-orchestrator.yaml
  - prompt-cache.yaml
  - safety-gateway.yaml
  - model-router.yaml
  - inference-pool.yaml
  - web-app.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: workshop
    includeSelectors: false
